name: CQ

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Java 11
        uses: actions/setup-java@v1
        with:
          # Minimum required version for spotless dependencies
          java-version: 11

      - name: Download Node.js latest
        uses: actions/setup-node@v2-beta
        with:
          node-version: "*"

      - name: Install Node dependencies
        run: npm ci

      - name: Run tests
        run: npm test
