name: Update

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  fetch:
    runs-on: ubuntu-latest
    continue-on-error: true

    outputs:
      kotlin: ${{ steps.fetch-kotlin-version.outputs.result }}
      this: ${{ steps.fetch-this-version.outputs.result }}

    steps:
      - name: Fetch latest Kotlin version
        uses: seancroach/latest-stable-version-action@main
        id: fetch-kotlin-version
        with:
          owner: JetBrains
          repo: kotlin

      - name: Log latest Kotlin version
        run: echo ${{ steps.fetch-kotlin-version.outputs.result }}

      - name: Fetch latest tag
        uses: seancroach/latest-stable-version-action@main
        id: fetch-this-version
        with:
          owner: aetherite-dev
          repo: kotlin

      - name: Log this latest version
        run: echo ${{ steps.fetch-this-version.outputs.result }}

  update:
    runs-on: ubuntu-latest
    needs: fetch
    if: needs.fetch.outputs.kotlin != needs.fetch.outputs.this

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ELEVATED_GITHUB_TOKEN }}

      - name: Download Java Latest
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Update plugin
        run: ./gradlew build -Pversion=${{ needs.fetch.outputs.kotlin }}

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "chore(release): v${{ needs.fetch.outputs.kotlin }}" --no-verify

      - name: Create tag
        run: git tag v${{ needs.fetch.outputs.kotlin }}

      - name: Push changes
        run: git push origin v${{ needs.fetch.outputs.kotlin }} --no-verify
